services:
  - type: web
    name: shl-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port 8000
    runtime: python
    repo: https://github.com/Parth09090/Assesment-Recomendation-System
    branch: main
    plan: free

  - type: web
    name: shl-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
    runtime: python
    repo: https://github.com/Parth09090/Assesment-Recomendation-System
    branch: main
    plan: free
